//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleMenu.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimeNumber", ReplyAction="http://tempuri.org/IService1/PrimeNumberResponse")]
        bool PrimeNumber(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrimeNumber", ReplyAction="http://tempuri.org/IService1/PrimeNumberResponse")]
        System.Threading.Tasks.Task<bool> PrimeNumberAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumOfDigits", ReplyAction="http://tempuri.org/IService1/SumOfDigitsResponse")]
        int SumOfDigits(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SumOfDigits", ReplyAction="http://tempuri.org/IService1/SumOfDigitsResponse")]
        System.Threading.Tasks.Task<int> SumOfDigitsAsync(int num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        string ReverseString(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ReverseString", ReplyAction="http://tempuri.org/IService1/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHTMLTAGs", ReplyAction="http://tempuri.org/IService1/PrintHTMLTAGsResponse")]
        string PrintHTMLTAGs(string tag, int data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PrintHTMLTAGs", ReplyAction="http://tempuri.org/IService1/PrintHTMLTAGsResponse")]
        System.Threading.Tasks.Task<string> PrintHTMLTAGsAsync(string tag, int data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        string SortNumbers(string sort, string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SortNumbers", ReplyAction="http://tempuri.org/IService1/SortNumbersResponse")]
        System.Threading.Tasks.Task<string> SortNumbersAsync(string sort, string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ConsoleMenu.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ConsoleMenu.ServiceReference1.IService1>, ConsoleMenu.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PrimeNumber(int num) {
            return base.Channel.PrimeNumber(num);
        }
        
        public System.Threading.Tasks.Task<bool> PrimeNumberAsync(int num) {
            return base.Channel.PrimeNumberAsync(num);
        }
        
        public int SumOfDigits(int num) {
            return base.Channel.SumOfDigits(num);
        }
        
        public System.Threading.Tasks.Task<int> SumOfDigitsAsync(int num) {
            return base.Channel.SumOfDigitsAsync(num);
        }
        
        public string ReverseString(string str) {
            return base.Channel.ReverseString(str);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string str) {
            return base.Channel.ReverseStringAsync(str);
        }
        
        public string PrintHTMLTAGs(string tag, int data) {
            return base.Channel.PrintHTMLTAGs(tag, data);
        }
        
        public System.Threading.Tasks.Task<string> PrintHTMLTAGsAsync(string tag, int data) {
            return base.Channel.PrintHTMLTAGsAsync(tag, data);
        }
        
        public string SortNumbers(string sort, string data) {
            return base.Channel.SortNumbers(sort, data);
        }
        
        public System.Threading.Tasks.Task<string> SortNumbersAsync(string sort, string data) {
            return base.Channel.SortNumbersAsync(sort, data);
        }
    }
}
